### PR TITLE
Custom teleport revamped

### PR DESCRIPTION
**Pull request by harlanx**
- Added teleport-through-list functionality.
  - Teleport only to items with checkmark
  - Added Previous and Next Hotkey in Custom Teleport
  - Added Custom Teleport Enable Hotkey entry in Hotkeys menu
  - Added Custom Teleport entry with current teleport name to Active Features Status
- List are now using natural sort instead of ascii sort
- Easier removal of teleports
- TP Button is now next to it's nodes
- Fix search clearing when losing focus

If there's better implementation or refactoring needed please feel free to revise.

<details>
<summary>Preview</summary>

https://user-images.githubusercontent.com/78299538/174570412-ef77b9ae-a84f-4322-9d99-70532a0ae327.mp4

</details>

### CODE REVIEW

**Comment by harlanx** [comment]
> Where `alphanum.hpp` uses, and why it's in `cheat-base/events/helpers/`?

it's used for natural sorting.
I don't know where to put it so I just put it in any helper folder.

|Before|Alphanum|
|-|-|
|A1|A1|
|A10|A2|
|A11|A3|
|A12|A10|
|A2|A11|
|A3|A12|

**Comment by Fanixtar** [comment]
i think c++ already have shlwapi.h for natural string comparer, StrCmpLogicalW()
it's the one used by windows explorer

**Comment by harlanx** [comment]
> i think c++ already have shlwapi.h for natural string comparer, StrCmpLogicalW() it's the one used by windows explorer

Thanks! I didn't know about that.

**Comment by Legend-Recalls** [comment]
wow this is pretty much ultimate but can a hotkey to pause be implemented?

**Comment by harlanx** [comment]
> wow this is pretty much ultimate but can a hotkey to pause be implemented?

It does not teleport automatically. You might want to use a macro to press with interval.

**Pull request merged**
