### PR TITLE
Finished AutoSeelie

### PR DESCRIPTION
**Pull request by m0nkrel**
Added ElectroSeelie support. Fixed ESP shacking.
Thanks to @Taiga74164 and @RyujinZX for the help.

https://user-images.githubusercontent.com/84017229/178045903-528457fa-48ed-409c-b760-a9d402b9618b.mp4

### CODE REVIEW

**Comment by Taiga74164** [comment]
harosh harosh 🤣

**Comment by RyujinZX** [comment]
> harosh harosh 🤣

vnature horosh horosh

**Comment by vyachnd** [comment]
As I know, `auto seelie` on `seelie` works when you approach it to _activate_ it, which is convenient because you can keep the function turned on on a permanent basis. With `electro seelie` this won't work anymore, because it may happen that you won't notice how he started flying. Perhaps it is worth dividing them or running only on those `electro seelie` that were activated once by the player, or another way

**Comment by m0nkrel** [comment]
Added button for Electro Seelie. If main button not activated - another will not appear.

**Pull request closed without merging**
