### PR TITLE
Fix unable to sprint issue

### PR DESCRIPTION
**Pull request by andiabrudan**
Hi all, I've got a fix for an issue I'm sure we all experienced with the `infinite stamina` cheat: quitting the game with it enabled and being unable to sprint when starting back up. (Or just going into Serenitea Pot with it enabled).

So I did some digging/logging and I found that [this one line](https://github.com/Akebi-Group/Akebi-GC/blob/fc657f144c88a0865a6a740975cad2dfc5c2f537/cheat-library/src/user/cheat/player/InfiniteStamina.cpp#L60) was causing the issue (kind of). Let me explain.

When the game starts (that is, you load into the game proper), those 3 `propTypes` fire. They all need to be disabled for the cheat to work correctly but at the same time, they need to execute at least once to initialize some data on the client. If these props never execute, you will be unable to dash, climb or do other activities that involve stamina consumption.

So, the fix is pretty simple: execute them only once.
But there's a problem with that: how do I know when those props fire in the code?
Well, as it turns out, there's an easy fix for that as well: use a prop that fires only once, at the beginning of the game.
There aren't a lot of these, but I assume I can count on `PROP_PLAYER_LEVEL` to only fire once.

And there you have it: If the code sees that the current protType is `PROP_PLAYER_LEVEL`, it will set a flag to true which will let everything execute. When the propType is `PROP_MAX_STAMINA`, we set that flag to false, and we no longer execute any of those 3 props. This also has the advantage to work when you switch realms to Serenitea Pot and back.
(Note: I chose `PROP_MAX_STAMINA` because it always fires last of those 3. In all my testing, those 3 props always fired in the same order and `PROP_MAX_STAMINA` was always last. Checking only for this saves a bit of execution, but you could add `if` statements for all propTypes individually)

In any case, I hope you like the change. I had to move the condition a bit higher because of the logic involved there.
Feel free to make any modifications as you feel necessary.

(P.S. you don't need backslashes for strings in C++. The preprocessor removes newlines and whitespaces and in C++ any 2 strings "like " "these" are merged together if there aren't any other operators in between)

### CODE REVIEW

**Comment by Taiga74164** [comment]
whats your discord 👀

**Comment by andiabrudan** [comment]
Andi#1655

**Comment by andiabrudan** [comment]
^ Upon further investigation, it looks like propType `PROP_PLAYER_LEVEL` was not a good choice to begin with.
And neither was `PROP_PLAYER_WORLD_LEVEL_LIMIT` which sometimes executed after the props for stamina.
Yesterday, I was testing the changes on a high level account which doesn't level up very fast.
But today I logged into a low level account and upon gaining some XP, my level increased which broke the flag I introduced causing the cheat to be always off.

Thankfully, I revised my logic and came up with the solution I have in the latest commit. This activates the cheat only when the first prop for stamina is seen and deactivates it after the last. This works much better.
Here's [some logs](https://github.com/Akebi-Group/Akebi-GC/files/9022952/genshin.logs.txt) to visualize what's happening.

One caveat here is that if you use some of your stamina then immediately change realms, there will be a visual artifact of the stamina bar stuck at whatever the real value was when you switched worlds. This won't affect the cheat in any way, but it's annoying to see on the screen

**Comment by CPP-Callow** [comment]
Thanks for your detail description of your solution. I think, I approve it now, but I think we should find more strong method to determine when we should pass the value.

**Pull request merged**
