### PR TITLE
Add option to hide features from status window

### PR DESCRIPTION
**Pull request by FawazTakhji**
GenshinImpact_D95MRcOYAJ

### CODE REVIEW

**Comment by cip300** [comment]
Why ? when you just can hide

**Comment by FawazTakhji** [comment]
> Why ? when you just can hide it from settings

you can hide individual features while allowing other features to show up on the window

**Comment by CallowBlack** [comment]
I don't like this way to solve this problem. You can modify only CheatManagerBase instead adding field to all features.

**Comment by FawazTakhji** [comment]
I don't know how

**Pull request closed without merging**
