### PR TITLE
Improve AutoCook feature

### PR DESCRIPTION
**Pull request by TerraFaster**
Added a dropdown where user can choose cooking quality from listed qualities (Suspicious, Normal and Delicious).

### CODE REVIEW

**Comment by HexChap** [comment]
Great idea

**Comment by Taiga74164** [comment]
(

image

**Comment by TerraFaster** [comment]
> image

I was asleep when you wrote this post ¯\\\_(ツ)\_/¯.

Here's the solution (for all users):
• Open main directory where you have **injector.exe** and...
1. Open your **cfg.json** file, find **"QualityField"** field and set it's value to **"Normal"** with these quotes. **OR**
2. Just **delete** your **cfg.json** file...

**Comment by Taiga74164** [comment]
oh i forgot to check mine 💀

**Comment by CR4Player** [comment]
after i edited cfg.json and relaunch the game, it wiped my profile...all settings and saved map info are gone...😣

**Comment by Taiga74164** [comment]
> after i edited cfg.json and relaunch the game, it wiped my profile...all settings and saved map info are gone...😣

you could've just removed AutoCook only (

**Comment by Shichiha** [comment]
check your recycle bin

**Comment by CR4Player** [comment]
> check your recycle bin

thank god i have a daily backup, everything is ok now.


> > after i edited cfg.json and relaunch the game, it wiped my profile...all settings and saved map info are gone...😣
> 
> you could've just removed AutoCook only (

yeah, delete whole "Auto Cook" section works.

**Comment by junatok** [comment]
please fix auto seeli i have new account when i try auto selli in dragonspine it doesn't work

**Pull request merged**
