### PR TITLE
Texture Changer

### PR DESCRIPTION
**Pull request by RyujinZX**
Character Texture Change:
image
Free Texture: https://disk.yandex.ru/d/VMrNWpCIHC2JJA

### CODE REVIEW

**Comment by Taiga74164** [comment]
HAHAHHAHA

**Comment by Taiga74164** [comment]
check [Textures](https://github.com/zeroruka/GI_Assets) :eyes:

**Comment by Taiga74164** [comment]
<details>
  <summary>REAL (NSFW)</summary>
  
</details>

**Comment by CNLouisLiu** [comment]
wow

**Comment by tedzify** [comment]
Oh my...

**Comment by Screenatyouruse** [comment]
callow accept this pr asap, it will benefit akebi users greatly :D

**Comment by Emilia33** [comment]
i hope this not very banable :>

**Comment by decausedinside** [comment]
> 

how use .dds files in this texture manager.

**Comment by ATF-zero** [comment]
Can only .png files be used?

**Comment by milkboy77** [comment]
W...TF...

**Comment by alt3ri** [comment]
omg real

**Comment by skycon8** [comment]
Anyway to convert .dds to useable .png ? or suggestion of any link to get more .png texture?

**Comment by Taiga74164** [comment]
> Anyway to convert .dds to useable .png ? or suggestion of any link to get more .png texture?

just export dds to png in photoshop

**Comment by skycon8** [comment]
thanks, will try.

**Pull request merged**
