### PR TITLE
Chinese

### PR DESCRIPTION
**Pull request by Vision-996**
Hello, I need to pull the Chinese version

### CODE REVIEW

**Comment by m0nkrel** [comment]
wtf

**Comment by Vision-996** [comment]
Sorry, I don't think I'm very good at using git

**Comment by Taiga74164** [comment]
well at least close it right away ....

**Comment by Vision-996** [comment]
为什么我没有找到关闭按钮， 你能告诉我它在哪里吗

**Comment by Vision-996** [comment]
why i didn't find the close button can you tell me where it is

**Comment by Vision-996** [comment]
It looks like it's closed, then I'm relieved

**Pull request closed without merging**
