### PR TITLE
Feature: Glider Texture Changer

### PR DESCRIPTION
**Pull request by gawgua**
Just a bunch of mess
- Add text to indicate the current Glider like with the Avatar
- Add texture change for glider (mix from [Ryujin](https://github.com/RyujinZX) Avatar Tex Change and [portra](https://github.com/portra400nc) ModelChanger)

### CODE REVIEW

**Comment by Taiga74164** [comment]
Looks good!
image

<details>
  <summary>NSFW</summary>
  
</details>

**Comment by zxcgeorgy** [comment]
and what command and where to enter?

**Comment by gawgua** [comment]
Visual>TextureChanger at the bottom

**Comment by zxcgeorgy** [comment]
you can png the airframe which is in 1 screenshot taiga74164

**Comment by zxcgeorgy** [comment]
can I take a photo of the glider that taiga74164 has in the first screenshot?

**Comment by Taiga74164** [comment]
Source: AGMG

Rainbow F
red_dragon_wings

**Comment by zxcgeorgy** [comment]
> Source: AGMG
> 
> Rainbow F red_dragon_wings

thank you so much, can I contact you at Discord? I have a suggestion that you can add to the cheat. my Discord Akebi#9904

**Comment by llsf88** [comment]
> 

to change the dress do you use this cheat or you are using 3DMigoto? because I can only change the color, not the way they look

**Pull request merged**
