### PR TITLE
Add Golden Apple Archipelago interactive map data

### PR DESCRIPTION
**Pull request by Fanixtar**
image

also add missing ImagingConch and EchoingConch images

Solve #285

### CODE REVIEW

**Comment by hellomykami** [comment]
ops. you did this before me 😆

**Comment by Taiga74164** [comment]
for those 2 conches, do they show on ESP too?
(sorry, couldn't check it my self since too busy with other stuff)

**Comment by m0nkrel** [comment]
> for those 2 conches, do they show on ESP too? (sorry, couldn't check it my self since too busy with other stuff)

i can pr this

**Comment by m0nkrel** [comment]
@hellomykami `SimpleFilter EchoShell = { app::EntityType__Enum_1::EchoShell,{ "_Echoconch","_Dreamconch"}};`

**Comment by CallowBlack** [comment]
I pushed #290, so I'll close it. Thank you for your work.

**Pull request closed without merging**
