### PR TITLE
changed menu's and moved combat stuff

### PR DESCRIPTION
**Pull request by biswop**
changed menu's to collapsing headers and moved combat stuff to a combat tab

world
image

combat
image

hotkeys
image

### CODE REVIEW

**Review by Shichiha — CHANGES_REQUESTED** [review]
just change [this part in the code](https://github.com/Akebi-Group/Akebi-GC/blob/9e214c15006d131dfd9859f60a5685ffd54950e6/cheat-base/src/cheat-base/cheat/CheatManagerBase.cpp#L115-L126) to:
```cpp
void CheatManagerBase::DrawMenuSection(const std::string& sectionName, const std::vector<Feature*>& features) const
{
	if (ImGui::CollapsingHeader(sectionName.c_str()))
	{
		for (auto& feature : features)
		{
			ImGui::PushID(&feature);
			feature->DrawMain();
			ImGui::PopID();
		}
	}
}
```

can you re-do it with this implementation?

**Comment by biswop** [comment]
> just change [this part in the code](https://github.com/Akebi-Group/Akebi-GC/blob/9e214c15006d131dfd9859f60a5685ffd54950e6/cheat-base/src/cheat-base/cheat/CheatManagerBase.cpp#L115-L126) to:
> 
> ```c++
> void CheatManagerBase::DrawMenuSection(const std::string& sectionName, const std::vector<Feature*>& features) const
> {
> 	if (ImGui::CollapsingHeader(sectionName.c_str()))
> 	{
> 		for (auto& feature : features)
> 		{
> 			ImGui::PushID(&feature);
> 			feature->DrawMain();
> 			ImGui::PopID();
> 		}
> 	}
> }
> ```
> 
> can you re-do it with this implementation?

so I have done that and got everything just about the way it was but I'm left with a blank dropdown with nothing in it, in the world tab
image

**Comment by Shichiha** [comment]
oops, add an additional if statement `if (!sectionName.empty())`
so it will be like this
```cpp
{
	if (!sectionName.empty())
		if (ImGui::CollapsingHeader(sectionName.c_str()))
		{
			for (auto &feature : features)
			{
				ImGui::PushID(&feature);
				feature->DrawMain();
				ImGui::PopID();
			}
		}
}
```

**Comment by Shichiha** [comment]
It works, but try to fix `ESP`, `Hotkeys`, `Settings` tabs, where there are features with no section 🤭 

Best of luck

**Comment by biswop** [comment]
sort of got it, made it where `esp`, `hotkeys` and `settings` have there own dropdowns

image
image
image

debug was also affected when adding `if (!sectionName.empty())` so its got a dropdown as well

image

**Comment by biswop** [comment]
#444 did it better than I did

**Comment by Shichiha** [comment]
good work though 😉

**Pull request closed without merging**
