### PR TITLE
3.0 game update (OS version)

### PR DESCRIPTION
**Pull request by Taiga74164**
## Priority:
- [x] Update offsets
- [x] Check structs for new fields or shuffled Proto fields(very important)

## Minor things todo:
- [x] Remove unused stuff from previous patch
- [x] Assembly checksum
- [x] Update for CN
- [x] Update README for new things added

## ESP Checklist:
- [x] Featured
- [x] Guide
- [x] Living
- [x] Monsters
- [x] Plants
- [x] Puzzles

## Interactive Map Checklist:
- [x] Update ``map_teyvat.json`` for Sumeru
- [x] Update filters

## Notes
- Icons for Living, Monsters, and Plants have been added on https://github.com/Akebi-Group/Akebi-GC/commit/e2fa0c0cf616165db827a42d4f1237bc08720c12 and https://github.com/Akebi-Group/Akebi-GC/commit/ecf7c69ff72fe865e17e99ea663ba5a0a039cce2

## Issues fixed:
- #449

### CODE REVIEW

**Comment by Taiga74164** [comment]
structs looks good for now. time to play ToF 🤣 

image

**Comment by OzymoGit** [comment]
merge it

**Comment by azhdaha-100kg** [comment]
when it's gonna 14/14 ?😶

**Comment by Bannyfelt13** [comment]
when can :(

**Comment by tonygiao123456** [comment]
no release?how to use,sir

**Comment by Fanixtar** [comment]
> no release?how to use,sir

they are updating it, you may check again in a few hours

**Comment by OzymoGit** [comment]
> no release?how to use,sir

go to his fork you can build it

**Comment by tonygiao123456** [comment]
knew,thanks

**Comment by tonygiao123456** [comment]
> 

thanks

**Comment by tonygiao123456** [comment]
> > no release?how to use,sir
> 
> go to his fork you can build it

thanks

**Comment by chongWjing** [comment]
thanks for your hard work

**Comment by suaibiyx163** [comment]
Listen to me say thank you,Because of you,Warmed up for four seasons.

**Comment by OzymoGit** [comment]
nice

**Comment by soulsad228** [comment]
можно ли уже скачать для версии 3.0?

**Comment by Gsutab-M** [comment]
Looking forward to this update

**Comment by PixelHir** [comment]
[Release-x64.zip](https://github.com/Akebi-Group/Akebi-GC/files/9415815/Release-x64.zip)
I compiled the 3.0 version myself
Naturally you shouldn't trust me since I could've added anything to it, but if you're that lazy to trust me here you go
[Virustotal here](https://www.virustotal.com/gui/file/3482bc35f0688b6cb459285c7e0e22927f4082e018538c6408ea073626894115?nocache=1)

**Comment by Lunairayz** [comment]
> [Release-x64.zip](https://github.com/Akebi-Group/Akebi-GC/files/9415815/Release-x64.zip) I compiled the 3.0 version myself

or just [go to actions](https://github.com/Akebi-Group/Akebi-GC/actions/workflows/main.yml?query=branch%3Amaster) LMAO moron

**Comment by PixelHir** [comment]
> > [Release-x64.zip](https://github.com/Akebi-Group/Akebi-GC/files/9415815/Release-x64.zip) I compiled the 3.0 version myself
> 
> or just [go to actions](https://github.com/Akebi-Group/Akebi-GC/actions/workflows/main.yml) LMAO moron

didn't see this repo has actions set up mb, but great you have to call me moron over that lol

**Comment by Lunairayz** [comment]
butthurt over pixels on a piece of plastic

**Comment by ClickClack7531** [comment]
> [Release-x64.zip](https://github.com/Akebi-Group/Akebi-GC/files/9415815/Release-x64.zip) I compiled the 3.0 version myself Naturally you shouldn't trust me since I could've added anything to it, but if you're that lazy to trust me here you go (best if you compile it yourself, please do that actually) [Virustotal here](https://www.virustotal.com/gui/file/3482bc35f0688b6cb459285c7e0e22927f4082e018538c6408ea073626894115?nocache=1)

I am new to github. How exactly do you compile/build something?

**Comment by Lunairayz** [comment]
> > [Release-x64.zip](https://github.com/Akebi-Group/Akebi-GC/files/9415815/Release-x64.zip) I compiled the 3.0 version myself Naturally you shouldn't trust me since I could've added anything to it, but if you're that lazy to trust me here you go (best if you compile it yourself, please do that actually) [Virustotal here](https://www.virustotal.com/gui/file/3482bc35f0688b6cb459285c7e0e22927f4082e018538c6408ea073626894115?nocache=1)
> 
> I am new to github. How exactly do you compile/build something?

using visual studio, simple shit but if you wanna do it easy mode, [u could go here](https://github.com/Akebi-Group/Akebi-GC/actions)

**Comment by ClickClack7531** [comment]
> 

I wont mind using software to manually "compile" it. I just dont know how nor what compiling is :/

**Pull request merged**
