### PR TITLE
Added avatar and npc to the ESP

### PR DESCRIPTION
**Pull request by NctimeAza**
at ESP-Living

Avatar ESP: Optionally display Avatar for own or teammate

image

### CODE REVIEW

**Comment by CPP-Callow** [comment]
Can you rename it to camel style? Because name parser will add space automatically.

**Comment by harlanx** [comment]
now we just wait for windtrace rerun 😄

**Comment by Taiga74164** [comment]
lol HvH

**Comment by alt3ri** [comment]
so true

**Pull request merged**
