### PR TITLE
RapidFire Changes

### LINKED ISSUE #10: `Multi hit` issue with few characters
This was in previous repo. 
When multi hit is on few characters charged attack doesn't do any damage.
I found below characters have the problem. there may be others also.

~~- Ayaka, Zhongli, Xiangling **charged attack**~~ (fixed August 7, 2022)

~~- Xiao's E doesn't do any damage when multi hit is on.~~ (fixed August 6, 2022)

### LINKED ISSUE #73: Multi-hit does not work on previous character's elemental burst after switching character
When using a character's elemental burst that stays on the field for a while, then you switch to another character, the multi-hit does not work anymore for that particular elemental burst. It goes back to single value.

For example, when I'm using Venti's burst, Multi-hit works as normal on his burst when he is still on the field. Though when I switched to another character, his burst damage revert back to single value. This bug applies to any character's elemental burst that stays on the field to deal damage, whether it is Ayaka, Ayato or Venti.

Date Occured: Multiple times and it is always
Is it reproducible: Yes, just use any character's elemental burst that stays on the field, and then switch to another character, then the multi-hit damage does not work anymore.
Release Version: 0.75

### LINKED ISSUE #98: Yelan charge burst shot does not work if the `Multi hit` is on
when multi hit is on the yelan charge burst attack does not work when it is turned off it works properly but when turned on enemies do not take damage

### PR DESCRIPTION
**Pull request by Taiga74164**
## Requires testing
- [x] Fixed #73 
- [x] Fixed #98 
- [x] Fixed #10 
- [x] Added Multi-Animation Rapid Fire [Request from Discord](https://discord.com/channels/440536354544156683/986013153437548594/1004329740393521254)

Basically filtered it the same way I did for XYZ. If you want to debug you can check ``[rbx]`` which is equivalent to ``MoleMole_BaseEntity`` in ``MoleMole_LCBaseCombat_DoHitEntity`` function.

Ayaka's charged attack should be fixed with this method. **Polearm character's charged attack still needs to be fixed.**

### CODE REVIEW

**Comment by Taiga74164** [comment]
Multi-Animation:

https://user-images.githubusercontent.com/67109235/183235818-4a813d47-a18f-4af5-a654-ee84a39d7cd0.mp4

https://user-images.githubusercontent.com/67109235/183235822-52fb7e05-4a32-4a15-b64b-34cacc642587.mp4

**Comment by souvikpodder** [comment]
Hoping to use xiao again. .🥺

**Comment by Taiga74164** [comment]
> Hoping to use xiao again. .🥺

xiao's E should be fixed..

**Comment by Taiga74164** [comment]
fixed. uwooghhh


https://user-images.githubusercontent.com/67109235/183280504-720f6d9b-9772-4483-bf64-497ef85a4344.mp4

**Review by Shichiha — APPROVED** [review]
LGTM!

**Pull request merged**
