### PR TITLE
Add teleportation automation on custom teleport

### LINKED ISSUE #221: Add timed custom teleports
Is it possible to make it so that after you mark certain custom teleport points, you can just have the game automatically teleport to each of them in turn on a timer (like, teleport, wait 5 seconds, teleport again). With crash damage on and auto-looting on, you can then automate the Elite enemy farming process.

### LINKED ISSUE #443: Automatic teleportation by points with a choice of delay
Add a function that allows you to automatically teleport between points. It would be nice if it was possible to adjust the delay between these teleports.

This function will be very useful, because many people use clickers to activate teleportation binds. It is strange that akebi still does not have such a function (

### PR DESCRIPTION
**Pull request by harlanx**
* Closes #221 
* Closes #443

### CODE REVIEW

**Comment by harlanx** [comment]
> Скриншот 10-08-2022 174939 I am getting an error while uploading json file.

Can you upload the json file. I'll look into it later.

**Comment by OzymoGit** [comment]
can you share teleport coordinates json for al oculus?

**Comment by harlanx** [comment]
> can you share teleport coordinates json for al oculus?

You can just search it on [cheat-library/res/map_teyvat.json](https://github.com/Akebi-Group/Akebi-GC/blob/master/cheat-library/res/map_teyvat.json) It' used for the interactive map but it doesn't have the z-coordinates  and some may not be very accurate.

**Comment by OzymoGit** [comment]
please make a working json for oculus so we blockhead can use this

**Comment by Taiga74164** [comment]
> please make a working json for oculus so we blockhead can use this

Its in our [discord](https://discord.com/channels/440536354544156683/986021186532163685/997911438456803431)

**Comment by OzymoGit** [comment]
> > please make a working json for oculus so we blockhead can use this
> 
> Its in our [discord](https://discord.com/channels/440536354544156683/986021186532163685/997911438456803431)

thanks, can we have an update version of this for sumeru too?

**Pull request merged**
