### PR TITLE
add golden apple archipelago interactive map data and conches to esp

### PR DESCRIPTION
**Pull request by hellomykami**
thanks to  #289 #287 .

### CODE REVIEW

**Comment by L3mri** [comment]
phantasmal conches not found

**Comment by hellomykami** [comment]
> phantasmal conches not found

phantasmal conches ? can you post a picture

**Comment by azhdaha-100kg** [comment]
update pls

**Comment by llsf88** [comment]
hi, can we have phantasmal conches to ESP please?

**Comment by hellomykami** [comment]
so what is phantasmal conches ? can somebody give me a picture?

**Comment by FawazTakhji** [comment]
> so what is phantasmal conches ? can somebody give me a picture?

they're inside the domains I think

**Comment by hellomykami** [comment]
there 2 conch. imaging conch and echoing conch. 
the conch in domains is one of them

**Pull request merged**
