### PR TITLE
2.8 game update

### PR DESCRIPTION
**Pull request by Taiga74164**
### Updated everything to 2.8

**Some notes:**
- I didn't rename some of the functions to their actual name since I didn't wanna go through changing everything in each cpp file 🤣 (see comments on top of the function).
- Tested on 2.7.54 beta and 2.8 rel
- Removed Music Event. Will come back whenever the event gets a re-run.
- ``Animator_set_avatar`` in ``unityplayer-functions`` is for Model Changer feature (will be used later).

**Known Issues:**
- ~~``Kill Aura: Instant Mode``  doesn't work. It might be because I tested with Private Server.~~
- Offsets on Chinese client aren't the same anymore (discuss on Discord on what to do).😭 

**TODOs**
- DLL Checksum
- Some testing

image

### CODE REVIEW

**Comment by NctimeAza** [comment]
OMG

**Comment by alt3ri** [comment]
Yo that was fast

**Comment by talhakaanozkan** [comment]
thanks @Taiga74164

**Comment by zhouqingyi1127** [comment]
哇哦！这么快

**Comment by redclif43** [comment]
wow

**Comment by sadmess** [comment]
为什么他可以同时编队这么多角色

**Comment by Badsha71** [comment]
Thanks a lot 😌

**Comment by Fanixtar** [comment]
pog

**Comment by RyujinZX** [comment]
Nice Work blyad **+Rep**

**Review by khawkong — APPROVED** [review]

**Comment by hellomykami** [comment]
Chinese client's metadata and dll are different to global's. 😭

**Comment by Taiga74164** [comment]
> 

yea seems like they they applied these changes on 2.8 :sob:

**Comment by hellomykami** [comment]
> > Chinese client's metadata and dll are different to global's. 😭
> 
> 
> 
> yea seems like they they applied these changes on 2.8 :sob:

😔 should to find two different offsets . sad

**Comment by fajriwip** [comment]
very nice, thanks for the update

**Comment by nstennyz** [comment]
thank for update

**Comment by hellomykami** [comment]
@Taiga74164 so can you accept Discord invitation

**Comment by VaVe-Xit** [comment]
wait wait im confused how do i use this for 2.8?

**Comment by zgy22506** [comment]
pog

**Comment by Gsutab-M** [comment]
Can't Chinese clients enjoy it?  :( :(

**Comment by CR4Player** [comment]
> Can't Chinese clients enjoy it? :( :(

Confirmed working on CN server.

**Comment by Gsutab-M** [comment]
> 

Really?  :D

**Comment by Gsutab-M** [comment]
> > 中国客户不能享受吗？:( :(
> 
> 已确认在CN服务器上工作。

Really? :D

**Comment by CR4Player** [comment]
> > > 中国客户不能享受吗？:( :(
> > 
> > 
> > 已确认在CN服务器上工作。
> 
> Really? :D

for branch ‘chinese-2.8’ yes, you need to compile by yourself though.

**Comment by Gsutab-M** [comment]
> > > > 中国客户不能享受吗？:( :(
> > > 
> > > 
> > > 已确认在CN服务器上工作。
> > 
> > 
> > Really? :D
> 
> for branch ‘chinese-2.8’ yes, you need to compile by yourself though.

Thanks

**Comment by CR4Player** [comment]
> > > Can't Chinese clients enjoy it? :( :(
> > 
> > 
> > Confirmed working on CN server.
> > can you teach me？

[https://github.com/Akebi-Group/Akebi-GC/releases/tag/v0.8]
CPP-Callow just updated recent release, I guess you don't have to build by youself now~ just download 'akebi-gc-v0.8-g2.8-binaries-chinese.zip'

**Comment by Gsutab-M** [comment]
> > > > 中国客户不能享受吗？:( :(
> > > 
> > > 
> > > 已确认在CN服务器上工作。你能教我吗？
> 
> [https://github.com/Akebi-Group/Akebi-GC/releases/tag/v0.8] CPP-Callow刚刚更新了最近的版本，我想你现在不必自己构建〜只需下载“akebi-gc-v0.8-g2.8-binaries-chinese.zip”

Many thanks! :D

**Pull request merged**
