### PR TITLE
Add user configurable items to VacuumLoot

### PR DESCRIPTION
**Pull request by andiabrudan**
Hi all,
I've been using VacuumLoot recently and I was annoyed about the crystalflies holding me up in the air.
So I've decided the best thing to do would be to let the user decide what they want to vacuum.

There are a couple of things I want to iron out before it's ready to merge:

1. Please help with `TreeNode`. The items don't want to group under the dropdown Q.Q
This happens at line 33 in the .cpp
Untitled-1

2. In the config file, the options save like so. How can I remove the duplicate keys and have everything top-level.
Untitled

3. Help with the config names in general. Some of them, I don't even know what they do.
For example, how is `_Thundercrystaldrop` different from `_Ore_ElectricRock` and what is `Eff_Animal`?
@Taiga74164 maybe you can answer ^ since you wrote the original.

4. Do you think these filters need tooltip descriptions? I think some items like "general loot" and "ore drops" might, but that could be fixed with a better name instead. If you want descriptions, I can add a LOTR easteregg next to potatoes: "**Po-ta-toes! Boil em, mash em, stick em in a stew**"

5. I noticed `Noctilucous Jade` is not vacuumed. If you have any idea how to find the entity name for it, please help.

So far, I've tested it and it works as intended. I was able to vacuum loot to me, dynamically change the config, and walk away from it. It's just visual stuff that needs some wrangling.

### CODE REVIEW

**Comment by Taiga74164** [comment]
Those are ``GameObject names`` you can find them in the ``Debug`` tab as well

**Comment by andiabrudan** [comment]
All right!
All of the issues mentioned above have been fixed and I'm happy with the results. Here's how the menu looks now.
Note, the `Loot Types` is collapsible, so once you set it how you like, you can close the menu and forget about it.
Untitled

**Comment by andiabrudan** [comment]
^ I moved the vacuum location in front of the player (like Mob Vacuum does).
Most ores were fine being underneath the player, but I've noticed Noctilucous Jade is a larger object, has collision, and pushed the player up when vacuumed.

**Comment by harlanx** [comment]
Can you allow edit? I can't seem to push to your fork branch.

Here's how it'll look btw
I'll let you decide which to add in the filters on this feature, it's your PR anyway though you can ask for other's input if you're unsure.
I haven't tried all the new filters and maybe there's more...

VacuumLoot

<details>
<summary>Config Entry Sample</summary>

```yaml
            "VacuumLoot": {
                "DelayTime": 905,
                "Distance": 3.5999999046325684,
                "Filters": {
                    "Equipment": {
                        "Artifacts": false,
                        "Bow": false,
                        "Sword": false
                    },
                    "Featured": {
                        "Item Drops": false
                    },
                    "Living": {
                        "Eel": false,
                        "Lizard Tail": false
                    },
                    "Mineral": {
                        "Amethyst Lump": false,
                        "Amethyst Lump Drop": false,
                        "Archaic Stone": false,
                        "Cor Lapis": false,
                        "Crystal Chunk Drop": false,
                        "Electro Crystal": false,
                        "Electro Crystal Drop": false,
                        "Iron Chunk": false,
                        "Iron Chunk Drop": false,
                        "Magical Crystal Chunk Drop": false,
                        "Noctilucous Jade": false,
                        "Noctilucous Jade Drop": false,
                        "Scarlet Quartz Drop": false,
                        "Starsilver": false,
                        "Starsilver Drop": false,
                        "White Iron Chunk": false,
                        "White Iron Chunk Drop": false
                    }
                },
                "Radius": 6.400000095367432
            },
```

</details>

**Comment by andiabrudan** [comment]
Thank you @harlanx, very nice.
Just want to point out that I commented out the entries for whole mineral chunks. I think that goes a bit against the spirit of this option (which is to vacuum loot drops, not the entities that drop the loot themselves).
Gotta say, this looks much better now.

**Pull request merged**
